#!/bin/bash

cd /tmp ;
wget https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts ;
sudo rm /etc/hosts ;
sudo cp /etc/main_hosts /etc/hosts ;
sudo cat /tmp/hosts >> /etc/hosts ;
sudo /etc/init.d/networking restart ;

