#!/bin/bash
cd /tmp ;
tmphostsloc="/tmp/adds-free-hosts-tmp";

rm /etc/hosts ;
cp /etc/main_hosts /etc/hosts ;

fetchHosts (){
	wget $1 -O $tmphostsloc;
	sudo cat $tmphostsloc >> /etc/hosts ;
}

fetchHosts https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts ;
fetchHosts https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts ;
fetchHosts https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt ;
fetchHosts https://raw.githubusercontent.com/shreyasminocha/shady-hosts/main/hosts ;
fetchHosts https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt ;

/etc/init.d/networking restart ;

